## This file is a general .xdc for the Basys3 rev B board

# Clock signal
set_property PACKAGE_PIN W5 [get_ports EXTCLK]
	set_property IOSTANDARD LVCMOS33 [get_ports EXTCLK]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports EXTCLK]

# Switches
set_property PACKAGE_PIN V17 [get_ports {IOPA[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPA[0]}]
set_property PACKAGE_PIN V16 [get_ports {IOPA[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPA[1]}]
set_property PACKAGE_PIN W16 [get_ports {IOPA[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPA[2]}]
set_property PACKAGE_PIN W17 [get_ports {IOPA[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPA[3]}]
set_property PACKAGE_PIN W15 [get_ports {IOPA[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPA[4]}]
set_property PACKAGE_PIN V15 [get_ports {IOPA[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPA[5]}]
set_property PACKAGE_PIN W14 [get_ports {IOPA[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPA[6]}]
set_property PACKAGE_PIN W13 [get_ports {IOPA[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPA[7]}]
set_property PACKAGE_PIN V2 [get_ports {IOPA[8]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPA[8]}]
set_property PACKAGE_PIN T3 [get_ports {IOPA[9]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPA[9]}]
set_property PACKAGE_PIN T2 [get_ports {IOPA[10]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPA[10]}]
set_property PACKAGE_PIN R3 [get_ports {IOPA[11]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPA[11]}]
set_property PACKAGE_PIN W2 [get_ports {IOPA[12]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPA[12]}]
set_property PACKAGE_PIN U1 [get_ports {IOPA[13]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPA[13]}]
set_property PACKAGE_PIN T1 [get_ports {IOPA[14]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPA[14]}]
set_property PACKAGE_PIN R2 [get_ports {IOPA[15]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPA[15]}]


# LEDs
set_property PACKAGE_PIN U16 [get_ports {IOPB[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPB[0]}]
set_property PACKAGE_PIN E19 [get_ports {IOPB[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPB[1]}]
set_property PACKAGE_PIN U19 [get_ports {IOPB[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPB[2]}]
set_property PACKAGE_PIN V19 [get_ports {IOPB[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPB[3]}]
set_property PACKAGE_PIN W18 [get_ports {IOPB[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPB[4]}]
set_property PACKAGE_PIN U15 [get_ports {IOPB[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPB[5]}]
set_property PACKAGE_PIN U14 [get_ports {IOPB[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPB[6]}]
set_property PACKAGE_PIN V14 [get_ports {IOPB[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPB[7]}]
set_property PACKAGE_PIN V13 [get_ports {IOPB[8]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPB[8]}]
set_property PACKAGE_PIN V3 [get_ports {IOPB[9]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPB[9]}]
set_property PACKAGE_PIN W3 [get_ports {IOPB[10]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPB[10]}]
set_property PACKAGE_PIN U3 [get_ports {IOPB[11]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPB[11]}]
set_property PACKAGE_PIN P3 [get_ports {IOPB[12]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPB[12]}]
set_property PACKAGE_PIN N3 [get_ports {IOPB[13]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPB[13]}]
set_property PACKAGE_PIN P1 [get_ports {IOPB[14]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPB[14]}]
set_property PACKAGE_PIN L1 [get_ports {IOPB[15]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPB[15]}]


#7 segment display
set_property PACKAGE_PIN W7 [get_ports {seg[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]

set_property PACKAGE_PIN V7 [get_ports dp]
 	set_property IOSTANDARD LVCMOS33 [get_ports dp]

set_property PACKAGE_PIN U2 [get_ports {an[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property PACKAGE_PIN U4 [get_ports {an[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property PACKAGE_PIN V4 [get_ports {an[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property PACKAGE_PIN W4 [get_ports {an[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]


##Buttons
set_property PACKAGE_PIN U18 [get_ports HARDRESET]
	set_property IOSTANDARD LVCMOS33 [get_ports HARDRESET]

set_property PACKAGE_PIN T18 [get_ports {IOPC[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPC[0]}]
set_property PACKAGE_PIN W19 [get_ports {IOPC[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPC[1]}]
set_property PACKAGE_PIN T17 [get_ports {IOPC[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPC[2]}]
set_property PACKAGE_PIN U17 [get_ports {IOPC[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {IOPC[3]}]

##VGA Connector
set_property PACKAGE_PIN G19 [get_ports {vgaRed_top_ICOBS[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed_top_ICOBS[0]}]
set_property PACKAGE_PIN H19 [get_ports {vgaRed_top_ICOBS[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed_top_ICOBS[1]}]
set_property PACKAGE_PIN J19 [get_ports {vgaRed_top_ICOBS[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed_top_ICOBS[2]}]
set_property PACKAGE_PIN N19 [get_ports {vgaRed_top_ICOBS[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed_top_ICOBS[3]}]
set_property PACKAGE_PIN N18 [get_ports {vgaBLue_top_ICOBS[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {vgaBLue_top_ICOBS[0]}]
set_property PACKAGE_PIN L18 [get_ports {vgaBLue_top_ICOBS[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {vgaBLue_top_ICOBS[1]}]
set_property PACKAGE_PIN K18 [get_ports {vgaBLue_top_ICOBS[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {vgaBLue_top_ICOBS[2]}]
set_property PACKAGE_PIN J18 [get_ports {vgaBLue_top_ICOBS[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {vgaBLue_top_ICOBS[3]}]
set_property PACKAGE_PIN J17 [get_ports {vgaGreen_top_ICOBS[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen_top_ICOBS[0]}]
set_property PACKAGE_PIN H17 [get_ports {vgaGreen_top_ICOBS[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen_top_ICOBS[1]}]
set_property PACKAGE_PIN G17 [get_ports {vgaGreen_top_ICOBS[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen_top_ICOBS[2]}]
set_property PACKAGE_PIN D17 [get_ports {vgaGreen_top_ICOBS[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen_top_ICOBS[3]}]
set_property PACKAGE_PIN P19 [get_ports Hsync_top_ICOBS]
	set_property IOSTANDARD LVCMOS33 [get_ports Hsync_top_ICOBS]
set_property PACKAGE_PIN R19 [get_ports Vsync_top_ICOBS]
	set_property IOSTANDARD LVCMOS33 [get_ports Vsync_top_ICOBS]

##USB-RS232 Interface
set_property PACKAGE_PIN B18 [get_ports UART_RX]
	set_property IOSTANDARD LVCMOS33 [get_ports UART_RX]
set_property PACKAGE_PIN A18 [get_ports UART_TX]
	set_property IOSTANDARD LVCMOS33 [get_ports UART_TX]
